workflows:
  flutter-app:
    name: Flutter Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: Fetch Flutter dependencies
        script: flutter pub get

      - name: Run tests
        script: flutter test

      - name: Build iOS
        script: |
          flutter build ipa --release --no-codesign
          mkdir -p build/ios/ipa
          mv build/ios/archive/MyApp.xcarchive build/ios/ipa/

      - name: Build Android
        script: flutter build apk --release

    artifacts:
      - build/**/outputs/**/*.apk
      - build/ios/ipa/*.ipa

