workflows:
  android-build:
    name: Android APK Build
    max_build_duration: 30
    instance_type: mac_pro  # استخدام جهاز mac_pro لموارد أكثر
    environment:
      vars:
        PACKAGE_NAME: "com.hulectures.myapp"  # ضع اسم الباكيج هنا
      flutter: stable  # إذا كان مشروعك Flutter
      node: latest     # إذا كان يستخدم npm

    scripts:
      - name: Clean up disk space
        script: |
          df -h
          rm -rf ~/.gradle/caches/
          rm -rf ~/.gradle/wrapper/
          rm -rf ~/.pub-cache/
          df -h

      - name: Install dependencies (إذا كان مشروعك npm)
        script: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build APK
        script: |
          if [ -d android ]; then
            cd android
            ./gradlew assembleRelease
          fi

    artifacts:
      - android/app/build/outputs/**/*.apk  # حفظ ملف APK النهائي
