workflows:
  web-app:
    name: Web Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      node: latest  # يستخدم أحدث إصدار من Node.js

    scripts:
      - name: Install dependencies (إذا كنت تستخدم npm)
        script: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Build project (إذا كنت تستخدم أدوات مثل Webpack أو Vite)
        script: |
          if [ -f package.json ]; then
            npm run build
          fi

    artifacts:
      - build/  # مسار مجلد الإخراج النهائي (إذا كنت تبني المشروع)

    publishing:
      email:
        recipients:
          - "hu.lectures.abdo@gmail.com"  # استبدلها ببريدك الإلكتروني
