workflows:
  android-app:
    name: Android APK Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.hulectures.myapp"  # استبدلها بحزمة تطبيقك
      node: latest
      java: 17  # تأكد من استخدام إصدار متوافق مع مشروعك

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease

    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk  # هذا هو ملف APK النهائي

    publishing:
      email:
        recipients:
          - "hu.lectures.abdo@gmail.com"
