workflows:
  android-apk:
    name: Build Android APK
    instance_type: mac_mini_m1
    environment:
      node: latest
    scripts:
      - name: تثبيت Cordova والاعتماديات
        script: |
          npm install -g cordova
          cordova create myApp
          cd myApp
          cordova platform add android
          cp -r $CM_CLONE_DIR/* myApp/www/
      - name: بناء APK
        script: |
          cd myApp
          cordova build android
    artifacts:
      - myApp/platforms/android/app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - "hu.lectures.abdo@gmail.com"  # ضع بريدك الإلكتروني هنا
